"""Direct Polymarket fallback planning surface.

This package is intentionally non-executing in its first slice. It can build
gate decisions and deterministic ledger records, but it does not submit,
cancel, replace, or prepare orders.
"""

from codex_tools.polymarket.execution_gate import (
    PolymarketExecutionGateSnapshot,
    PolymarketFallbackDecision,
    PolymarketFallbackIntent,
    build_fallback_decision,
    derive_idempotency_key,
)
from codex_tools.polymarket.ledger import (
    PolymarketFallbackLedgerWrite,
    build_ledger_entry,
    default_fallback_ledger_root,
    write_fallback_decision_ledger,
)
from codex_tools.polymarket.preview import (
    PREVIEW_SCHEMA_VERSION,
    PolymarketFallbackPreview,
    build_fallback_preview,
)
from codex_tools.polymarket.safety import (
    DEFAULT_DIRECT_TRUTH_MAX_AGE_SECONDS,
    DEFAULT_MIN_BUY_NOTIONAL_USD,
    DEFAULT_MIN_ORDER_SIZE,
    PolymarketSafetyCheck,
    build_polymarket_safety_gate_snapshot,
    evaluate_direct_truth_freshness,
    evaluate_kill_switch,
    evaluate_minimum_order_policy,
    evaluate_risk_budget,
    evaluate_target_stop_rebuy_policy,
)
from codex_tools.polymarket.account import (
    ACCOUNT_SNAPSHOT_SCHEMA_VERSION,
    PolymarketAccountReadSnapshot,
    read_account_snapshot,
)
from codex_tools.polymarket.grid_service import (
    GRID_SERVICE_SCHEMA_VERSION,
    PolymarketGridCandidate,
    PolymarketGridServicePreview,
    build_grid_service_preview,
)
from codex_tools.polymarket.settlement import (
    NO_REDEMPTION_STATEMENT,
    POST_REDEEM_RECONCILIATION_SCHEMA_VERSION,
    REDEEM_PREVIEW_SCHEMA_VERSION,
    REQUIRED_REDEEM_GATE_LABELS,
    RESIDUAL_CLASSIFICATION_SCHEMA_VERSION,
    SETTLEMENT_LEDGER_ENTRY_SCHEMA_VERSION,
    SETTLEMENT_LEDGER_FILE_NAME,
    SETTLEMENT_LEDGER_WRITE_SCHEMA_VERSION,
    SETTLEMENT_READINESS_REPORT_SCHEMA_VERSION,
    PolymarketPostRedeemReconciliation,
    PolymarketRedeemPreview,
    PolymarketResidualClassification,
    PolymarketSettlementReadinessReport,
    PolymarketSettlementLedgerWrite,
    build_post_redeem_reconciliation,
    build_redeem_preview,
    build_settlement_ledger_entry,
    build_settlement_readiness_report,
    classify_documented_residual_positions,
    classify_resolved_market_residual,
    default_settlement_ledger_root,
    derive_redeem_idempotency_key,
    extract_settlement_residual_metadata,
    write_settlement_ledger_prewrite,
)

__all__ = [
    "ACCOUNT_SNAPSHOT_SCHEMA_VERSION",
    "DEFAULT_DIRECT_TRUTH_MAX_AGE_SECONDS",
    "DEFAULT_MIN_BUY_NOTIONAL_USD",
    "DEFAULT_MIN_ORDER_SIZE",
    "GRID_SERVICE_SCHEMA_VERSION",
    "NO_REDEMPTION_STATEMENT",
    "POST_REDEEM_RECONCILIATION_SCHEMA_VERSION",
    "PREVIEW_SCHEMA_VERSION",
    "REDEEM_PREVIEW_SCHEMA_VERSION",
    "REQUIRED_REDEEM_GATE_LABELS",
    "RESIDUAL_CLASSIFICATION_SCHEMA_VERSION",
    "SETTLEMENT_LEDGER_ENTRY_SCHEMA_VERSION",
    "SETTLEMENT_LEDGER_FILE_NAME",
    "SETTLEMENT_LEDGER_WRITE_SCHEMA_VERSION",
    "SETTLEMENT_READINESS_REPORT_SCHEMA_VERSION",
    "PolymarketAccountReadSnapshot",
    "PolymarketExecutionGateSnapshot",
    "PolymarketFallbackDecision",
    "PolymarketFallbackIntent",
    "PolymarketFallbackLedgerWrite",
    "PolymarketFallbackPreview",
    "PolymarketGridCandidate",
    "PolymarketGridServicePreview",
    "PolymarketPostRedeemReconciliation",
    "PolymarketRedeemPreview",
    "PolymarketResidualClassification",
    "PolymarketSettlementReadinessReport",
    "PolymarketSafetyCheck",
    "PolymarketSettlementLedgerWrite",
    "build_fallback_decision",
    "build_fallback_preview",
    "build_grid_service_preview",
    "build_ledger_entry",
    "build_polymarket_safety_gate_snapshot",
    "build_post_redeem_reconciliation",
    "build_redeem_preview",
    "build_settlement_ledger_entry",
    "build_settlement_readiness_report",
    "classify_documented_residual_positions",
    "classify_resolved_market_residual",
    "default_fallback_ledger_root",
    "default_settlement_ledger_root",
    "derive_idempotency_key",
    "derive_redeem_idempotency_key",
    "evaluate_direct_truth_freshness",
    "evaluate_kill_switch",
    "evaluate_minimum_order_policy",
    "evaluate_risk_budget",
    "evaluate_target_stop_rebuy_policy",
    "extract_settlement_residual_metadata",
    "read_account_snapshot",
    "write_fallback_decision_ledger",
    "write_settlement_ledger_prewrite",
]
