from __future__ import annotations

from collections.abc import Iterable
from typing import Any

from crypto_options_app.signals.validation.models import SignalCandidateSpec, build_signal_id, model_to_dict


FAMILY = "master_hedge_grid_scalping"


def list_signal_specs() -> tuple[SignalCandidateSpec, ...]:
    return ALL_SIGNAL_SPECS


def get_signal_spec(signal_id: str) -> SignalCandidateSpec | None:
    return _BY_ID.get(signal_id)


def signal_catalog_summary() -> dict[str, Any]:
    rows = [model_to_dict(spec) | {"structural_blockers": list(spec.structural_blockers())} for spec in ALL_SIGNAL_SPECS]
    by_type: dict[str, int] = {}
    by_block: dict[str, int] = {}
    for spec in ALL_SIGNAL_SPECS:
        by_type[spec.signal_type] = by_type.get(spec.signal_type, 0) + 1
        for block in spec.required_data_blocks:
            by_block[block] = by_block.get(block, 0) + 1
    return {
        "schema_version": "crypto_options_signal_catalog_v1",
        "family": FAMILY,
        "signal_count": len(ALL_SIGNAL_SPECS),
        "by_signal_type": by_type,
        "by_required_data_block": by_block,
        "signals": rows,
        "orders_allowed": False,
        "live_trading_authorized": False,
    }


def _spec(
    *,
    signal_type: str,
    sources: Iterable[str],
    variant: str,
    purpose: str,
    event_phase_relevance: str,
    refresh_rate_seconds: int | None,
    time_frames_relevant: tuple[str, ...],
    required_data_blocks: tuple[str, ...],
    validation_target: str,
    win_criteria: str,
    sample_unit: str,
    impact_if_degraded: str,
    description: str,
    signal_payload_example: dict[str, Any],
    parent_signal_id: str | None = None,
    supersedes_signal_id: str | None = None,
    version: str = "v1",
) -> SignalCandidateSpec:
    source_tuple = tuple(sources)
    signal_id = build_signal_id(
        family=FAMILY,
        signal_type=signal_type,
        sources=source_tuple,
        variant=variant,
        version=version,
    )
    return SignalCandidateSpec(
        signal_id=signal_id,
        family=FAMILY,
        signal_type=signal_type,
        sources=source_tuple,
        variant=variant,
        version=version,
        filename=f"{signal_id}.py",
        purpose=purpose,  # type: ignore[arg-type]
        event_phase_relevance=event_phase_relevance,  # type: ignore[arg-type]
        refresh_rate_seconds=refresh_rate_seconds,
        time_frames_relevant=time_frames_relevant,
        required_data_blocks=required_data_blocks,  # type: ignore[arg-type]
        validation_target=validation_target,
        win_criteria=win_criteria,
        sample_unit=sample_unit,
        impact_if_degraded=impact_if_degraded,  # type: ignore[arg-type]
        description=description,
        signal_payload_example=signal_payload_example,
        parent_signal_id=parent_signal_id,
        supersedes_signal_id=supersedes_signal_id,
    )


FIRST_BATCH_SIGNAL_SPECS: tuple[SignalCandidateSpec, ...] = (
    _spec(
        signal_type="outcome_prediction",
        sources=("profiles",),
        variant="top_distribution_cost_weighted",
        purpose="refreshing_stat",
        event_phase_relevance="live",
        refresh_rate_seconds=30,
        time_frames_relevant=("0:30-4:30 event elapsed",),
        required_data_blocks=("B",),
        validation_target="event resolved outcome and forward option-price movement",
        win_criteria="dominant cost-weighted profile side wins or reaches a configured favorable price before max adverse excursion",
        sample_unit="event_slug",
        impact_if_degraded="critical",
        description="Canonical top_profiles_distribution outcome/hedge signal using committed cost by high-grade profiles.",
        signal_payload_example={"distribution": {"up": 0.82, "down": 0.18}, "canonical_method": "cost_weighted"},
    ),
    _spec(
        signal_type="outcome_prediction",
        sources=("profiles",),
        variant="top_distribution_shares_weighted",
        purpose="refreshing_stat",
        event_phase_relevance="live",
        refresh_rate_seconds=30,
        time_frames_relevant=("0:30-4:30 event elapsed",),
        required_data_blocks=("B",),
        validation_target="event resolved outcome and side price at 1m, 3m, final",
        win_criteria="dominant share-weighted side outperforms opposite side after signal timestamp",
        sample_unit="event_slug",
        impact_if_degraded="high",
        description="Profile distribution variant that treats payout exposure as more important than notional spent.",
        signal_payload_example={"distribution": {"up": 0.76, "down": 0.24}, "canonical_method": "shares_weighted"},
    ),
    _spec(
        signal_type="outcome_prediction",
        sources=("profiles",),
        variant="top_distribution_count_consensus",
        purpose="logic_gate_trigger",
        event_phase_relevance="live",
        refresh_rate_seconds=30,
        time_frames_relevant=("0:30-4:30 event elapsed",),
        required_data_blocks=("B",),
        validation_target="profile consensus reliability",
        win_criteria="profile-count majority agrees with final or with cost-weighted side that reaches favorable excursion",
        sample_unit="event_slug",
        impact_if_degraded="medium",
        description="Consensus sanity check that prevents one whale-like profile from dominating without broad support.",
        signal_payload_example={"distribution": {"up": 0.62, "down": 0.38}, "canonical_method": "profile_count_weighted"},
    ),
    _spec(
        signal_type="outcome_prediction",
        sources=("cryptoprice",),
        variant="multiframe_trend_conflict",
        purpose="logic_gate_trigger",
        event_phase_relevance="both",
        refresh_rate_seconds=30,
        time_frames_relevant=("1m", "5m", "10m", "15m", "20m", "30m", "60m"),
        required_data_blocks=("A",),
        validation_target="first-minute and final event direction",
        win_criteria="trend-aligned side reaches favorable option-price target more often than conflicting-trend baseline",
        sample_unit="event_slug",
        impact_if_degraded="high",
        description="Detects whether short and medium crypto timeframes agree, conflict, or imply a likely breakout/convergence regime.",
        signal_payload_example={"regime": "conflicting_up_down", "direction": "down", "confidence": 0.61},
    ),
    _spec(
        signal_type="outcome_prediction",
        sources=("cryptoprice",),
        variant="external_observer_consensus",
        purpose="logic_gate_trigger",
        event_phase_relevance="both",
        refresh_rate_seconds=30,
        time_frames_relevant=("1m", "5m", "15m"),
        required_data_blocks=("A",),
        validation_target="external technical observer direction vs event path",
        win_criteria="IFCM/TradersUnion consensus direction improves first-minute side selection over neutral baseline",
        sample_unit="event_slug",
        impact_if_degraded="medium",
        description="Uses external technical summaries as a confirm/avoid gate, not as a primary execution signal.",
        signal_payload_example={"ifcm_1m": "Sell", "ifcm_5m": "Sell", "observer_consensus": "down"},
    ),
    _spec(
        signal_type="outcome_prediction",
        sources=("optionprice",),
        variant="first_minute_momentum",
        purpose="refreshing_stat",
        event_phase_relevance="live",
        refresh_rate_seconds=30,
        time_frames_relevant=("0s", "10s", "30s", "60s"),
        required_data_blocks=("C",),
        validation_target="option price movement after event open",
        win_criteria="side with stronger first-minute option momentum keeps favorable mark-to-market edge or wins",
        sample_unit="event_token_pair",
        impact_if_degraded="high",
        description="Measures whether the option market is rapidly repricing a side in the first minute.",
        signal_payload_example={"up_delta_30s": 0.12, "down_delta_30s": -0.10, "direction": "up"},
    ),
    _spec(
        signal_type="side_start",
        sources=("profiles",),
        variant="pre_event_distribution",
        purpose="strategy_parameter",
        event_phase_relevance="pre",
        refresh_rate_seconds=30,
        time_frames_relevant=("-15m", "-5m", "-60s", "-30s", "-10s"),
        required_data_blocks=("B",),
        validation_target="pre-event buying-ahead side vs early favorable excursion",
        win_criteria="dominant pre-event profile side reaches configured sell target before stop or opposing side",
        sample_unit="event_slug",
        impact_if_degraded="critical",
        description="Determines whether to start one-sided, two-sided, or flat based on high-grade buying ahead.",
        signal_payload_example={"side_start": "up", "distribution": {"up": 0.71, "down": 0.29}},
    ),
    _spec(
        signal_type="side_start",
        sources=("cryptoprice",),
        variant="target_relative_momentum",
        purpose="strategy_parameter",
        event_phase_relevance="pre",
        refresh_rate_seconds=30,
        time_frames_relevant=("1m", "5m", "15m"),
        required_data_blocks=("A",),
        validation_target="pre-event side start vs first 60s option excursion",
        win_criteria="selected side reaches +10c or configured target before adverse drawdown threshold",
        sample_unit="event_slug",
        impact_if_degraded="high",
        description="Uses target-relative crypto momentum to choose initial side or force neutral start.",
        signal_payload_example={"side_start": "down", "target_delta": -42.5, "momentum": "down"},
    ),
    _spec(
        signal_type="side_start",
        sources=("optionprice",),
        variant="pre_event_drift",
        purpose="strategy_parameter",
        event_phase_relevance="pre",
        refresh_rate_seconds=30,
        time_frames_relevant=("-15m", "-10m", "-5m", "-2m", "-60s", "-30s", "-10s"),
        required_data_blocks=("C",),
        validation_target="pre-event option drift vs early favorable excursion",
        win_criteria="drift-selected side reaches configured sell band before adverse drawdown",
        sample_unit="event_token_pair",
        impact_if_degraded="high",
        description="Uses captured pre-event Up/Down option price drift to decide whether upfront one-side buying is justified.",
        signal_payload_example={"side_start": "up", "up_pre_event_drift": 0.07, "down_pre_event_drift": -0.06},
    ),
    _spec(
        signal_type="trend_regime",
        sources=("cryptoprice",),
        variant="breakout_convergence_sideways",
        purpose="logic_gate_trigger",
        event_phase_relevance="both",
        refresh_rate_seconds=30,
        time_frames_relevant=("1m", "5m", "10m", "15m", "30m", "60m"),
        required_data_blocks=("A",),
        validation_target="event option path regime",
        win_criteria="regime label predicts whether event path is trend-efficient, choppy, or inversion-heavy",
        sample_unit="event_slug",
        impact_if_degraded="high",
        description="Classifies event setup as breakout, convergence, or sideways to choose whether grid/scalp should be dense or avoided.",
        signal_payload_example={"regime": "sideways_inversion_prone", "confidence": 0.58},
    ),
    _spec(
        signal_type="support_resistance",
        sources=("cryptoprice",),
        variant="ifcm_pivot_distance",
        purpose="price_reference",
        event_phase_relevance="both",
        refresh_rate_seconds=30,
        time_frames_relevant=("1m", "5m", "15m"),
        required_data_blocks=("A",),
        validation_target="rebound/resistance proximity vs option side reversal",
        win_criteria="near-pivot states produce statistically larger opposing-side rebound or lower continuation reliability",
        sample_unit="event_slug",
        impact_if_degraded="medium",
        description="Maps current BTC/ETH distance to external/local pivot bands for support/resistance awareness.",
        signal_payload_example={"nearest_band": "R1", "distance_bps": 7.2, "expected_rebound_side": "down"},
    ),
    _spec(
        signal_type="support_resistance",
        sources=("optionprice",),
        variant="bucket_rebound",
        purpose="price_reference",
        event_phase_relevance="both",
        refresh_rate_seconds=30,
        time_frames_relevant=("10c buckets", "30s range", "60s range"),
        required_data_blocks=("C",),
        validation_target="option price level touch and rebound behavior",
        win_criteria="configured bucket touches rebound by target cents within target seconds before deeper break",
        sample_unit="event_token_pair",
        impact_if_degraded="critical",
        description="Learns Up/Down option price levels that tend to bounce during crypto 5m events.",
        signal_payload_example={"side": "Down", "bucket": 0.20, "rebound_probability": 0.64},
    ),
    _spec(
        signal_type="buy_rebound",
        sources=("optionprice",),
        variant="touch_reclaim",
        purpose="logic_gate_trigger",
        event_phase_relevance="live",
        refresh_rate_seconds=30,
        time_frames_relevant=("30s", "60s", "full 5m event"),
        required_data_blocks=("C",),
        validation_target="buy trigger at touched option level",
        win_criteria="buy-side touch reclaims configured profit target before stop/settlement loss",
        sample_unit="event_token_pair",
        impact_if_degraded="critical",
        description="Directly validates underdog/favorite rebound buy triggers from option path, without executing a strategy.",
        signal_payload_example={"trigger": "buy_down_at_0.20", "target_sell": 0.25, "stop_reference": 0.12},
    ),
    _spec(
        signal_type="grid_spacing",
        sources=("optionprice",),
        variant="rolling_volatility_depth",
        purpose="strategy_parameter",
        event_phase_relevance="both",
        refresh_rate_seconds=30,
        time_frames_relevant=("30s", "60s", "5m"),
        required_data_blocks=("C",),
        validation_target="grid delta vs fill and exit opportunity",
        win_criteria="spacing captures enough fill-exit opportunities while avoiding over-dense unfilled or adverse fills",
        sample_unit="event_token_pair",
        impact_if_degraded="critical",
        description="Sets grid spacing from option path volatility and visible order-book depth.",
        signal_payload_example={"grid_spacing_cents": 4, "basis": "rolling_60s_range_depth_adjusted"},
    ),
    _spec(
        signal_type="grid_count",
        sources=("optionprice",),
        variant="depth_budget",
        purpose="strategy_parameter",
        event_phase_relevance="pre",
        refresh_rate_seconds=30,
        time_frames_relevant=("-2m", "-60s", "0s"),
        required_data_blocks=("C",),
        validation_target="initial ladder count vs budget/fillability",
        win_criteria="configured grid count maintains executable minimum notional and covers expected price path range",
        sample_unit="event_slug",
        impact_if_degraded="high",
        description="Determines how many initial grid levels fit the available budget and order-book depth.",
        signal_payload_example={"grid_count": 4, "min_order_notional": 1.0, "budget_required": 12.0},
    ),
    _spec(
        signal_type="grid_type",
        sources=("optionprice",),
        variant="inversion_frequency",
        purpose="strategy_parameter",
        event_phase_relevance="pre",
        refresh_rate_seconds=30,
        time_frames_relevant=("last_n_events", "current_event_first_60s"),
        required_data_blocks=("C",),
        validation_target="buy/sell grid vs buy-only hedge liquidation suitability",
        win_criteria="selected grid type improves simulated lifecycle PnL or lowers adverse exposure in matching regimes",
        sample_unit="event_slug",
        impact_if_degraded="high",
        description="Chooses standard buy/sell grid, buy-only paired hedge grid, or no grid based on inversion-heavy path statistics.",
        signal_payload_example={"grid_type": "paired_buy_sell", "avg_inversions": 4.2},
    ),
    _spec(
        signal_type="hedge_ratio",
        sources=("profiles",),
        variant="distribution_cost_weighted",
        purpose="refreshing_stat",
        event_phase_relevance="live",
        refresh_rate_seconds=30,
        time_frames_relevant=("0:30-4:30 event elapsed",),
        required_data_blocks=("B",),
        validation_target="target hedge distribution vs settlement and mark-to-market drawdown",
        win_criteria="profile-weighted target ratio improves outcome exposure over 50/50 or prior ratio baseline",
        sample_unit="event_slug",
        impact_if_degraded="critical",
        description="Translates top profile distribution into target Up/Down hedge proportions for managed strategy variants.",
        signal_payload_example={"target_exposure": {"up": 0.82, "down": 0.18}},
    ),
    _spec(
        signal_type="hedge_ratio",
        sources=("profiles", "optionprice"),
        variant="mark_to_distribution",
        purpose="refreshing_stat",
        event_phase_relevance="live",
        refresh_rate_seconds=30,
        time_frames_relevant=("0:30-4:30 event elapsed",),
        required_data_blocks=("B", "C"),
        validation_target="profile distribution adjusted by executable option prices",
        win_criteria="price-adjusted profile ratio improves simulated exposure return or reduces loss vs raw distribution",
        sample_unit="event_slug",
        impact_if_degraded="critical",
        description="Converts profile distribution into a cost-aware hedge target using current Up/Down executable prices.",
        signal_payload_example={"target_cost_ratio": {"up": 0.72, "down": 0.28}, "raw_distribution": {"up": 0.82, "down": 0.18}},
    ),
    _spec(
        signal_type="cashout_rebuy",
        sources=("optionprice",),
        variant="retrace_ladder",
        purpose="logic_gate_trigger",
        event_phase_relevance="live",
        refresh_rate_seconds=30,
        time_frames_relevant=("30s", "60s", "5m"),
        required_data_blocks=("C",),
        validation_target="sell target and rebuy target after favorable move",
        win_criteria="cashout target fills before reversal and rebuy target refills at lower cost often enough to beat hold baseline",
        sample_unit="event_token_pair",
        impact_if_degraded="critical",
        description="Validates the core sell-profit then rebuy-lower mechanic needed for managed hedge/grid/scalp.",
        signal_payload_example={"sell_target": 0.60, "rebuy_target": 0.48, "stale_after_seconds": 45},
    ),
    _spec(
        signal_type="stale_order_review",
        sources=("optionprice",),
        variant="spread_latency",
        purpose="logic_gate_trigger",
        event_phase_relevance="live",
        refresh_rate_seconds=30,
        time_frames_relevant=("30s", "60s"),
        required_data_blocks=("C",),
        validation_target="cancel/replace timing vs fillability and adverse selection",
        win_criteria="review rule reduces stale unfilled orders or adverse fills without reducing profitable fills too much",
        sample_unit="order_intent",
        impact_if_degraded="critical",
        description="Defines when resting orders should be reviewed or replaced using quote age, spread, and price movement.",
        signal_payload_example={"action": "replace", "quote_age_seconds": 42, "spread": 0.04},
    ),
    _spec(
        signal_type="final_minute",
        sources=("optionprice", "profiles"),
        variant="comeback_probability",
        purpose="logic_gate_trigger",
        event_phase_relevance="live",
        refresh_rate_seconds=30,
        time_frames_relevant=("final_60s", "last_n_events"),
        required_data_blocks=("B", "C"),
        validation_target="final minute underdog/favorite allocation",
        win_criteria="comeback/near-resolution label identifies when underdog buys have positive expected payoff or should be skipped",
        sample_unit="event_slug",
        impact_if_degraded="high",
        description="Evaluates whether final-minute underdog exposure is justified by option path and profile distribution.",
        signal_payload_example={"state": "near_resolved", "underdog_price": 0.13, "profile_distribution": {"up": 0.91, "down": 0.09}},
    ),
    _spec(
        signal_type="liquidity_depth",
        sources=("optionprice",),
        variant="top_depth_slippage",
        purpose="logic_gate_trigger",
        event_phase_relevance="both",
        refresh_rate_seconds=30,
        time_frames_relevant=("current_quote", "30s"),
        required_data_blocks=("C",),
        validation_target="fill feasibility at target notional",
        win_criteria="depth/slippage filter prevents unfillable or high-slippage simulated orders while preserving valid opportunities",
        sample_unit="event_token_pair",
        impact_if_degraded="critical",
        description="Guards every signal that implies execution by confirming enough visible depth and tolerable spread.",
        signal_payload_example={"max_notional_at_top3": 8.4, "spread": 0.02, "fillable": True},
    ),
    _spec(
        signal_type="latency_quality",
        sources=("cryptoprice", "optionprice", "profiles"),
        variant="freshness_gate",
        purpose="logic_gate_trigger",
        event_phase_relevance="both",
        refresh_rate_seconds=30,
        time_frames_relevant=("current_quote", "current_distribution", "current_underlying"),
        required_data_blocks=("A", "B", "C"),
        validation_target="data freshness and timestamp alignment",
        win_criteria="signals with fresh aligned A/B/C data outperform or avoid errors compared with stale/aligned-failed samples",
        sample_unit="decision_frame",
        impact_if_degraded="critical",
        description="Universal quality gate for every signal validation frame; no signal can pass promotion on stale data.",
        signal_payload_example={"max_source_age_seconds": 18.2, "aligned": True, "orders_allowed": False},
    ),
)


def _build_expanded_signal_specs() -> tuple[SignalCandidateSpec, ...]:
    """Generate the second signal universe for promotion discovery.

    The first 23 variants were enough to validate plumbing, but not enough to
    explore the space. These generated specs deliberately cover V2 repairs for
    weak rows plus new source/type combinations across A, B, C, and confluence
    mechanics.
    """

    rows: list[SignalCandidateSpec] = []
    used = {spec.signal_id for spec in FIRST_BATCH_SIGNAL_SPECS}

    def add(
        *,
        signal_type: str,
        sources: tuple[str, ...],
        variant: str,
        purpose: str,
        phase: str,
        blocks: tuple[str, ...],
        target: str,
        criteria: str,
        unit: str,
        impact: str,
        description: str,
        payload: dict[str, Any],
        parent_signal_id: str | None = None,
        supersedes_signal_id: str | None = None,
        frames: tuple[str, ...] = ("30s", "60s", "5m"),
        refresh: int | None = 30,
        version: str = "v1",
    ) -> None:
        spec = _spec(
            signal_type=signal_type,
            sources=sources,
            variant=variant,
            purpose=purpose,
            event_phase_relevance=phase,
            refresh_rate_seconds=refresh,
            time_frames_relevant=frames,
            required_data_blocks=blocks,
            validation_target=target,
            win_criteria=criteria,
            sample_unit=unit,
            impact_if_degraded=impact,
            description=description,
            signal_payload_example=payload,
            parent_signal_id=parent_signal_id,
            supersedes_signal_id=supersedes_signal_id,
            version=version,
        )
        if spec.signal_id not in used:
            used.add(spec.signal_id)
            rows.append(spec)

    # Targeted V2 repairs for rows that currently need review.
    weak_crypto_repairs = (
        ("outcome_prediction", "multiframe_trend_conflict", "agreement_only", "logic_gate_trigger", "high"),
        ("outcome_prediction", "multiframe_trend_conflict", "contrarian_filter", "logic_gate_trigger", "high"),
        ("outcome_prediction", "external_observer_consensus", "ifcm_1m_5m_alignment", "logic_gate_trigger", "medium"),
        ("side_start", "target_relative_momentum", "volatility_normalized", "strategy_parameter", "high"),
        ("trend_regime", "breakout_convergence_sideways", "non_directional_regime", "logic_gate_trigger", "high"),
        ("support_resistance", "ifcm_pivot_distance", "rebound_only_non_directional", "price_reference", "medium"),
        ("support_resistance", "ifcm_pivot_distance", "pivot_and_option_reclaim", "price_reference", "medium"),
    )
    for signal_type, base, suffix, purpose, impact in weak_crypto_repairs:
        add(
            signal_type=signal_type,
            sources=("cryptoprice",) if "option" not in suffix else ("cryptoprice", "optionprice"),
            variant=f"{base}_{suffix}",
            purpose=purpose,
            phase="both",
            blocks=("A",) if "option" not in suffix else ("A", "C"),
            target="strict replay outcome, regime, or rebound target with forward-return sanity check",
            criteria="must beat neutral/baseline and avoid negative average forward return in disjoint samples",
            unit="event_slug",
            impact=impact,
            description=f"V2 repair for {base}; separates weak directional claims from stricter observable trigger quality.",
            payload={"repair_for": base, "repair_variant": suffix, "requires_baseline": True},
            frames=("1m", "5m", "15m", "30m", "60m"),
            version="v2",
        )

    profile_variants = (
        "cost_confidence_60",
        "cost_confidence_70",
        "cost_confidence_80",
        "shares_confidence_60",
        "shares_confidence_70",
        "profile_count_supermajority",
        "s_plus_only_cost",
        "s_tier_only_cost",
        "one_sided_accounts_only",
        "hedger_accounts_only",
        "pre_event_only_60s",
        "live_delta_30s",
        "late_event_distribution_3m",
        "profile_entropy_low",
        "profile_whale_capped",
        "bonereaper_style_cluster",
    )
    for variant in profile_variants:
        add(
            signal_type="outcome_prediction",
            sources=("profiles",),
            variant=variant,
            purpose="refreshing_stat",
            phase="both" if "pre_event" in variant else "live",
            blocks=("B",),
            target="profile distribution side vs event outcome and favorable option excursion",
            criteria="dominant profile side must beat 50/50 baseline and retain positive forward option return",
            unit="event_slug",
            impact="critical" if "cost" in variant or "s_" in variant else "high",
            description=f"Profile distribution hypothesis using {variant.replace('_', ' ')} weighting/filtering.",
            payload={"distribution_method": variant, "output": {"up": 0.0, "down": 0.0}},
            frames=("pre_event", "0:30", "1:00", "2:30", "4:00"),
            version="v1",
        )

    hedge_variants = (
        "cost_ratio_min_conf_60",
        "cost_ratio_min_conf_75",
        "shares_ratio_min_conf_60",
        "cost_to_price_mark",
        "drawdown_adjusted_distribution",
        "profile_cluster_weighted",
        "late_distribution_rebalance",
        "entropy_reduced_rebalance",
        "opposite_side_rescue_ratio",
        "target_ratio_smoothing_ema",
    )
    for variant in hedge_variants:
        add(
            signal_type="hedge_ratio",
            sources=("profiles", "optionprice") if "price" in variant or "drawdown" in variant else ("profiles",),
            variant=variant,
            purpose="refreshing_stat",
            phase="live",
            blocks=("B", "C") if "price" in variant or "drawdown" in variant else ("B",),
            target="target Up/Down hedge ratio vs realized settlement and mark-to-market drawdown",
            criteria="target ratio must improve exposure return or reduce drawdown against 50/50 and prior-ratio baselines",
            unit="event_slug",
            impact="critical",
            description=f"Hedge-ratio signal variant for managed grid/scalp exposure using {variant.replace('_', ' ')}.",
            payload={"target_exposure": {"up": 0.0, "down": 0.0}, "method": variant},
            frames=("0:30", "1:00", "1:30", "2:00", "3:00", "4:00"),
            version="v1",
        )

    option_price_variants = (
        ("outcome_prediction", "first_10s_momentum", "refreshing_stat", "high"),
        ("outcome_prediction", "first_30s_momentum_reversal_guard", "refreshing_stat", "high"),
        ("outcome_prediction", "first_60s_favorite_hold", "refreshing_stat", "high"),
        ("side_start", "pre_event_15m_drift", "strategy_parameter", "high"),
        ("side_start", "pre_event_last_60s_reclaim", "strategy_parameter", "high"),
        ("support_resistance", "10c_bucket_touch", "price_reference", "critical"),
        ("support_resistance", "20c_underdog_rebound", "price_reference", "critical"),
        ("support_resistance", "40_60_midrange_inversion", "price_reference", "critical"),
        ("buy_rebound", "underdog_10c_to_12c", "logic_gate_trigger", "critical"),
        ("buy_rebound", "underdog_20c_to_25c", "logic_gate_trigger", "critical"),
        ("buy_rebound", "favorite_pullback_60c_reclaim", "logic_gate_trigger", "high"),
        ("grid_spacing", "30s_range_scaled", "strategy_parameter", "critical"),
        ("grid_spacing", "60s_range_scaled", "strategy_parameter", "critical"),
        ("grid_spacing", "swing_distance_scaled", "strategy_parameter", "critical"),
        ("grid_count", "top3_depth_budget_scaled", "strategy_parameter", "high"),
        ("grid_count", "near_50c_dense_budget", "strategy_parameter", "high"),
        ("grid_type", "inversion_heavy_buy_sell", "strategy_parameter", "high"),
        ("grid_type", "trend_efficient_buy_hold", "strategy_parameter", "high"),
        ("cashout_rebuy", "sell_10c_profit_rebuy_5c_lower", "logic_gate_trigger", "critical"),
        ("cashout_rebuy", "sell_20pct_profit_rebuy_midline", "logic_gate_trigger", "critical"),
        ("cashout_rebuy", "favorite_cashout_80c_rebuy_60c", "logic_gate_trigger", "critical"),
        ("stale_order_review", "replace_after_30s_spread_widen", "logic_gate_trigger", "critical"),
        ("stale_order_review", "cancel_final_90s_bad_spread", "logic_gate_trigger", "critical"),
        ("liquidity_depth", "top1_depth_min_notional", "logic_gate_trigger", "critical"),
        ("liquidity_depth", "top3_depth_slippage_guard", "logic_gate_trigger", "critical"),
        ("final_minute", "underdog_10_25c_comeback", "logic_gate_trigger", "high"),
        ("final_minute", "near_resolved_skip_underdog", "logic_gate_trigger", "high"),
    )
    for signal_type, variant, purpose, impact in option_price_variants:
        add(
            signal_type=signal_type,
            sources=("optionprice",),
            variant=variant,
            purpose=purpose,
            phase="pre" if variant.startswith("pre_event") else "live",
            blocks=("C",),
            target="Up/Down option price path, fillability, favorable excursion, or rebound behavior",
            criteria="must beat naive hold/skip baseline and preserve positive simulated forward value",
            unit="event_token_pair" if signal_type != "grid_count" else "event_slug",
            impact=impact,
            description=f"Option-path hypothesis for {signal_type} using {variant.replace('_', ' ')}.",
            payload={"option_signal": variant, "side": "up_or_down", "orders_allowed": False},
            frames=("-15m", "-5m", "0s", "10s", "30s", "60s", "300s"),
            version="v1",
        )

    crypto_variants = (
        ("outcome_prediction", "ema_slope_1m_5m_agreement", "logic_gate_trigger", "high"),
        ("outcome_prediction", "rsi_extreme_reversal", "logic_gate_trigger", "medium"),
        ("outcome_prediction", "macd_momentum_1m", "logic_gate_trigger", "medium"),
        ("outcome_prediction", "ifcm_strong_buy_sell_only", "logic_gate_trigger", "medium"),
        ("side_start", "pivot_distance_directional_gate", "strategy_parameter", "high"),
        ("side_start", "volatility_per_second_1h_normalized", "strategy_parameter", "high"),
        ("trend_regime", "ema_stack_convergence", "logic_gate_trigger", "high"),
        ("trend_regime", "bollinger_band_breakout_pressure", "logic_gate_trigger", "high"),
        ("support_resistance", "local_pivot_retest", "price_reference", "medium"),
        ("support_resistance", "external_pivot_cluster", "price_reference", "medium"),
        ("latency_quality", "observer_freshness_consensus", "logic_gate_trigger", "critical"),
    )
    for signal_type, variant, purpose, impact in crypto_variants:
        add(
            signal_type=signal_type,
            sources=("cryptoprice",),
            variant=variant,
            purpose=purpose,
            phase="both",
            blocks=("A",),
            target="underlying crypto indicator state vs first-minute and full-event option path",
            criteria="must beat neutral baseline and avoid negative forward return across disjoint samples",
            unit="event_slug",
            impact=impact,
            description=f"Crypto-indicator hypothesis using {variant.replace('_', ' ')}.",
            payload={"crypto_indicator": variant, "direction": "up_or_down_or_avoid"},
            frames=("1m", "5m", "15m", "30m", "60m"),
            version="v1",
        )

    confluence_variants = (
        ("outcome_prediction", ("profiles", "optionprice"), ("B", "C"), "profile_distribution_price_momentum_aligned", "refreshing_stat", "critical"),
        ("outcome_prediction", ("profiles", "cryptoprice"), ("A", "B"), "profile_distribution_crypto_trend_aligned", "refreshing_stat", "critical"),
        ("outcome_prediction", ("cryptoprice", "optionprice"), ("A", "C"), "crypto_pivot_option_reclaim", "logic_gate_trigger", "high"),
        ("outcome_prediction", ("cryptoprice", "optionprice", "profiles"), ("A", "B", "C"), "full_stack_directional_confluence", "refreshing_stat", "critical"),
        ("side_start", ("profiles", "optionprice"), ("B", "C"), "pre_event_profiles_price_drift_aligned", "strategy_parameter", "critical"),
        ("side_start", ("cryptoprice", "optionprice"), ("A", "C"), "crypto_momentum_option_drift_aligned", "strategy_parameter", "high"),
        ("side_start", ("cryptoprice", "optionprice", "profiles"), ("A", "B", "C"), "all_sources_start_side_agree", "strategy_parameter", "critical"),
        ("buy_rebound", ("cryptoprice", "optionprice"), ("A", "C"), "pivot_touch_option_reclaim", "logic_gate_trigger", "critical"),
        ("buy_rebound", ("profiles", "optionprice"), ("B", "C"), "profile_side_underdog_rebound", "logic_gate_trigger", "critical"),
        ("grid_spacing", ("cryptoprice", "optionprice"), ("A", "C"), "crypto_vol_option_vol_scaled", "strategy_parameter", "critical"),
        ("grid_count", ("cryptoprice", "optionprice"), ("A", "C"), "vol_depth_budget_grid_count", "strategy_parameter", "high"),
        ("grid_type", ("cryptoprice", "optionprice"), ("A", "C"), "trend_vs_inversion_selector", "strategy_parameter", "high"),
        ("hedge_ratio", ("cryptoprice", "optionprice", "profiles"), ("A", "B", "C"), "distribution_price_volatility_adjusted", "refreshing_stat", "critical"),
        ("cashout_rebuy", ("profiles", "optionprice"), ("B", "C"), "profile_target_cashout_rebuy", "logic_gate_trigger", "critical"),
        ("cashout_rebuy", ("cryptoprice", "optionprice"), ("A", "C"), "pivot_retrace_cashout_rebuy", "logic_gate_trigger", "critical"),
        ("stale_order_review", ("cryptoprice", "optionprice"), ("A", "C"), "vol_spread_latency_replace", "logic_gate_trigger", "critical"),
        ("final_minute", ("cryptoprice", "optionprice", "profiles"), ("A", "B", "C"), "comeback_vs_resolution_confluence", "logic_gate_trigger", "high"),
        ("liquidity_depth", ("profiles", "optionprice"), ("B", "C"), "profile_pressure_depth_guard", "logic_gate_trigger", "critical"),
        ("latency_quality", ("cryptoprice", "optionprice", "profiles"), ("A", "B", "C"), "abc_alignment_gate", "logic_gate_trigger", "critical"),
    )
    for signal_type, sources, blocks, variant, purpose, impact in confluence_variants:
        add(
            signal_type=signal_type,
            sources=sources,
            variant=variant,
            purpose=purpose,
            phase="both",
            blocks=blocks,
            target="confluence signal vs option path, final outcome, and simulated execution feasibility",
            criteria="must outperform each single-source component or justify being a strict gate",
            unit="decision_frame",
            impact=impact,
            description=f"Cross-source confluence hypothesis for {signal_type} using {variant.replace('_', ' ')}.",
            payload={"confluence": variant, "sources": list(sources), "decision": "signal_or_avoid"},
            frames=("-60s", "0:30", "1:00", "2:00", "3:00", "4:00"),
            version="v1",
        )

    crypto_option_confluence_waves = (
        (
            "outcome_prediction",
            "multiframe_conflict_option_path_alignment",
            "logic_gate_trigger",
            "high",
            "v2",
            "Outcome confluence that requires A multi-timeframe conflict/stack state to agree with C path direction, pair-sum stability, and rolling option volatility before choosing a side.",
        ),
        (
            "side_start",
            "observer_conflict_neutral_start_gate",
            "strategy_parameter",
            "high",
            "v3",
            "Side-start gate that defaults to neutral when external observer summaries conflict with C pre-event drift or pair-sum stability.",
        ),
        (
            "buy_rebound",
            "pivot_cluster_path_rebound_reclaim",
            "logic_gate_trigger",
            "critical",
            "v4",
            "Rebound confluence that requires A pivot/support context plus C rebound flips, rolling range expansion, and reclaim evidence before emitting a buy-rebound decision.",
        ),
        (
            "latency_quality",
            "observer_path_pair_sum_avoid_trade_gate",
            "logic_gate_trigger",
            "critical",
            "v5",
            "Avoid-trade gate that blocks A+C confluence decisions when technical observers are stale/conflicted, option pair sums are unstable, or path direction is too noisy for promotion-quality shadow evidence.",
        ),
        (
            "support_resistance",
            "pivot_distance_pair_sum_reference",
            "price_reference",
            "high",
            "v5",
            "Reference-only A+C support/resistance signal combining crypto pivot distance with C pair-sum stability and rebound zones.",
        ),
        (
            "grid_spacing",
            "crypto_option_path_volatility_reference",
            "strategy_parameter",
            "critical",
            "v5",
            "Reference-only A+C spacing signal combining crypto observer pressure, rolling option path volatility, and pair-sum stability.",
        ),
        (
            "trend_regime",
            "observer_path_conflict_reference",
            "price_reference",
            "high",
            "v5",
            "Reference-only A+C regime signal combining observer conflict, path direction flips, and pair-sum stability before any directional shadow claim.",
        ),
        (
            "side_start",
            "observer_pair_sum_stable_start_reference",
            "strategy_parameter",
            "high",
            "v5",
            "Reference-only A+C side-start signal that records a start side only when observer direction and stable option pair sums align; otherwise it records neutral.",
        ),
    )
    for signal_type, variant, purpose, impact, version, description in crypto_option_confluence_waves:
        add(
            signal_type=signal_type,
            sources=("cryptoprice", "optionprice"),
            variant=variant,
            purpose=purpose,
            phase="both",
            blocks=("A", "C"),
            target="A Crypto observer context combined with C Options path direction, pair-sum stability, rebound behavior, and execution feasibility",
            criteria="must improve or safely gate the generic A+C baseline without promoting stale-A directional evidence",
            unit="decision_frame",
            impact=impact,
            description=description,
            payload={
                "confluence": variant,
                "sources": ["cryptoprice", "optionprice"],
                "freshness_blocker_sensitive": True,
                "decision": "signal_or_avoid",
            },
            frames=("-60s", "-30s", "0:30", "1:00", "2:00", "3:00", "4:00"),
            version=version,
        )

    # Focused V2 expansions for high-scoring structural passes that still need strict replay/baseline tests.
    strict_replay_v2s = (
        ("buy_rebound", ("optionprice",), ("C",), "touch_reclaim_baseline_adjusted"),
        ("cashout_rebuy", ("optionprice",), ("C",), "retrace_ladder_baseline_adjusted"),
        ("grid_spacing", ("optionprice",), ("C",), "rolling_volatility_depth_out_of_sample"),
        ("liquidity_depth", ("optionprice",), ("C",), "top_depth_slippage_min_notional"),
        ("outcome_prediction", ("profiles",), ("B",), "top_distribution_cost_weighted_disjoint_events"),
        ("outcome_prediction", ("profiles",), ("B",), "top_distribution_shares_weighted_disjoint_events"),
        ("hedge_ratio", ("profiles",), ("B",), "distribution_cost_weighted_disjoint_events"),
        ("hedge_ratio", ("profiles", "optionprice"), ("B", "C"), "mark_to_distribution_disjoint_events"),
        ("side_start", ("profiles",), ("B",), "pre_event_distribution_disjoint_events"),
        ("stale_order_review", ("optionprice",), ("C",), "spread_latency_baseline_adjusted"),
        ("final_minute", ("optionprice", "profiles"), ("B", "C"), "comeback_probability_baseline_adjusted"),
    )
    for signal_type, sources, blocks, variant in strict_replay_v2s:
        add(
            signal_type=signal_type,
            sources=sources,
            variant=variant,
            purpose="refreshing_stat" if signal_type in {"outcome_prediction", "hedge_ratio"} else "logic_gate_trigger",
            phase="both",
            blocks=blocks,
            target="strict disjoint replay against naive baseline and synthetic-frame tautology checks",
            criteria="must remain positive after baseline adjustment and disjoint event sampling",
            unit="event_slug",
            impact="critical" if signal_type in {"buy_rebound", "hedge_ratio", "cashout_rebuy"} else "high",
            description=f"V2 strict-replay variant for {signal_type}; designed to prevent synthetic structural pass from being promoted directly.",
            payload={"strict_replay": True, "baseline_adjusted": True, "variant": variant},
            frames=("last_week_disjoint", "last_month_disjoint", "random_sample", "live_shadow"),
            version="v2",
        )

    # Third-wave remediation for crypto-only rows that still underperform as directional signals.
    # These convert weak directional claims into avoid gates, option-confirmed gates,
    # profile-confirmed gates, or non-directional regime parameters.
    remediation_waves = (
        ("outcome_prediction", "ema_slope_1m_5m_agreement", "option_confirmed", ("cryptoprice", "optionprice"), ("A", "C"), "v2"),
        ("outcome_prediction", "ema_slope_1m_5m_agreement", "profile_confirmed", ("cryptoprice", "profiles"), ("A", "B"), "v2"),
        ("outcome_prediction", "ema_slope_1m_5m_agreement", "avoid_conflict_only", ("cryptoprice",), ("A",), "v2"),
        ("outcome_prediction", "multiframe_trend_conflict", "option_confirmed", ("cryptoprice", "optionprice"), ("A", "C"), "v3"),
        ("outcome_prediction", "multiframe_trend_conflict", "profile_confirmed", ("cryptoprice", "profiles"), ("A", "B"), "v3"),
        ("outcome_prediction", "multiframe_trend_conflict", "avoid_conflict_only", ("cryptoprice",), ("A",), "v3"),
        ("outcome_prediction", "external_observer_consensus", "option_confirmed", ("cryptoprice", "optionprice"), ("A", "C"), "v3"),
        ("outcome_prediction", "external_observer_consensus", "profile_confirmed", ("cryptoprice", "profiles"), ("A", "B"), "v3"),
        ("outcome_prediction", "external_observer_consensus", "strong_only_avoid_gate", ("cryptoprice",), ("A",), "v3"),
        ("outcome_prediction", "ifcm_strong_buy_sell_only", "option_confirmed", ("cryptoprice", "optionprice"), ("A", "C"), "v2"),
        ("outcome_prediction", "macd_momentum_1m", "option_confirmed", ("cryptoprice", "optionprice"), ("A", "C"), "v2"),
        ("outcome_prediction", "rsi_extreme_reversal", "option_reclaim_confirmed", ("cryptoprice", "optionprice"), ("A", "C"), "v2"),
        ("side_start", "pivot_distance_directional_gate", "option_pre_drift_confirmed", ("cryptoprice", "optionprice"), ("A", "C"), "v2"),
        ("side_start", "pivot_distance_directional_gate", "profiles_pre_event_confirmed", ("cryptoprice", "profiles"), ("A", "B"), "v2"),
        ("side_start", "target_relative_momentum", "neutral_start_when_unconfirmed", ("cryptoprice",), ("A",), "v3"),
        ("side_start", "target_relative_momentum", "option_drift_confirmed", ("cryptoprice", "optionprice"), ("A", "C"), "v3"),
        ("side_start", "volatility_per_second_1h_normalized", "grid_density_only", ("cryptoprice", "optionprice"), ("A", "C"), "v2"),
        ("trend_regime", "breakout_convergence_sideways", "avoid_only", ("cryptoprice",), ("A",), "v3"),
        ("trend_regime", "breakout_convergence_sideways", "grid_density_gate", ("cryptoprice", "optionprice"), ("A", "C"), "v3"),
        ("trend_regime", "ema_stack_convergence", "option_path_confirmed", ("cryptoprice", "optionprice"), ("A", "C"), "v2"),
        ("trend_regime", "bollinger_band_breakout_pressure", "option_path_confirmed", ("cryptoprice", "optionprice"), ("A", "C"), "v2"),
        ("support_resistance", "ifcm_pivot_distance", "non_directional_grid_reference", ("cryptoprice",), ("A",), "v3"),
        ("support_resistance", "ifcm_pivot_distance", "option_rebound_only", ("cryptoprice", "optionprice"), ("A", "C"), "v3"),
        ("support_resistance", "ifcm_pivot_distance", "avoid_directional_claim", ("cryptoprice",), ("A",), "v3"),
        ("support_resistance", "ifcm_pivot_distance", "option_reclaim_positive_return_filter", ("cryptoprice", "optionprice"), ("A", "C"), "v4"),
        ("support_resistance", "ifcm_pivot_distance", "grid_reference_forward_return_guard", ("cryptoprice", "optionprice"), ("A", "C"), "v4"),
        ("latency_quality", "observer_freshness_consensus", "abc_freshness_required", ("cryptoprice", "optionprice", "profiles"), ("A", "B", "C"), "v2"),
        ("grid_type", "crypto_regime_selector", "option_inversion_confirmed", ("cryptoprice", "optionprice"), ("A", "C"), "v1"),
        ("grid_spacing", "crypto_volatility_spacing", "option_range_confirmed", ("cryptoprice", "optionprice"), ("A", "C"), "v1"),
        ("final_minute", "crypto_regime_comeback_filter", "option_profile_confirmed", ("cryptoprice", "optionprice", "profiles"), ("A", "B", "C"), "v1"),
    )
    for signal_type, base, suffix, sources, blocks, version in remediation_waves:
        purpose = "strategy_parameter" if signal_type in {"side_start", "grid_spacing", "grid_type"} else "logic_gate_trigger"
        if signal_type in {"support_resistance"}:
            purpose = "price_reference"
        if signal_type in {"latency_quality"}:
            purpose = "logic_gate_trigger"
        add(
            signal_type=signal_type,
            sources=sources,
            variant=f"{base}_{suffix}",
            purpose=purpose,
            phase="both",
            blocks=blocks,
            target="remediated weak directional signal as confluence, avoid gate, or non-directional strategy parameter",
            criteria="must avoid stale weak directional promotion and improve baseline-adjusted replay/live-shadow evidence",
            unit="decision_frame",
            impact="critical" if signal_type in {"latency_quality", "grid_spacing"} else "high",
            description=f"Remediation variant for {base}; converts weak standalone signal into {suffix.replace('_', ' ')}.",
            payload={"remediation_for": base, "mode": suffix, "promotion_requires_baseline": True},
            frames=("1m", "5m", "15m", "0:30", "1:00", "3:00"),
            version=version,
        )

    profile_consensus_revision_waves = (
        (
            "outcome_prediction",
            ("profiles",),
            ("B",),
            "splus_hedger_coherent_consensus",
            "refreshing_stat",
            "critical",
            "v4",
            "Consensus-only directional profile signal when S+ hedger pressure, reconstructed pair sum, and weighting methods all stay coherent.",
        ),
        (
            "outcome_prediction",
            ("profiles",),
            ("B",),
            "outcome_predictor_coherent_consensus",
            "refreshing_stat",
            "high",
            "v4",
            "Consensus-only directional profile signal when outcome_predictor style pressure is fresh, non-concentrated, and method-consistent.",
        ),
        (
            "hedge_ratio",
            ("profiles",),
            ("B",),
            "cost_share_alignment_reference",
            "refreshing_stat",
            "critical",
            "v5",
            "Reference for how tightly cost-weighted and shares-weighted profile distributions align before translating pressure into hedge size.",
        ),
        (
            "latency_quality",
            ("profiles",),
            ("B",),
            "profile_distribution_pair_sum_guard",
            "logic_gate_trigger",
            "critical",
            "v5",
            "Guard profile usage when reconstructed Up/Down profile price pair sums drift too far from executable sanity.",
        ),
    )
    for signal_type, sources, blocks, variant, purpose, impact, version, description in profile_consensus_revision_waves:
        add(
            signal_type=signal_type,
            sources=sources,
            variant=variant,
            purpose=purpose,
            phase="both" if signal_type == "outcome_prediction" else "live",
            blocks=blocks,
            target="profile-consensus coherence, pair-sum sanity, and weighting-method agreement before directional or hedge use",
            criteria="must stay positive after strict replay review and avoid promotion when freshness, pair sum, or weighting agreement degrades",
            unit="event_slug" if signal_type != "latency_quality" else "decision_frame",
            impact=impact,
            description=description,
            payload={"profile_consensus_revision": variant, "requires_component_breakdown": True},
            frames=("pre_event", "0:30", "1:00", "2:30", "4:00"),
            version=version,
        )

    # V5 building-block variants: these are not direct entry claims. They are
    # references, gates, and parameters that should strengthen strategy design
    # once they pass strict sample/diversity/hit-rate review.
    building_block_v5s = (
        (
            "hedge_ratio",
            ("profiles",),
            ("B",),
            "distribution_delta_reference",
            "refreshing_stat",
            "critical",
            "Profile Up/Down delta reference for hedge target sizing; direction is secondary to stable 30s reconstruction.",
        ),
        (
            "hedge_ratio",
            ("profiles",),
            ("B",),
            "reconstructed_profile_price_reference",
            "refreshing_stat",
            "critical",
            "Reconstructed profile-weighted Up/Down price reference derived from weighted cost and shares.",
        ),
        (
            "hedge_ratio",
            ("profiles",),
            ("B",),
            "grade_style_consensus_reference",
            "refreshing_stat",
            "critical",
            "Grade/style reference comparing S++/S+/S buckets and hedger vs outcome_predictor vs unknown pressure before sizing exposure.",
        ),
        (
            "latency_quality",
            ("profiles",),
            ("B",),
            "profile_distribution_freshness_gate",
            "logic_gate_trigger",
            "critical",
            "Gate profile distribution usage when profile snapshots are stale, sparse, or missing high-grade coverage.",
        ),
        (
            "latency_quality",
            ("profiles",),
            ("B",),
            "profile_distribution_method_agreement_gate",
            "logic_gate_trigger",
            "critical",
            "Gate profile usage when cost-weighted, shares-weighted, and count-weighted consensus diverge too far to treat pressure as coherent.",
        ),
        (
            "latency_quality",
            ("profiles",),
            ("B",),
            "profile_distribution_coverage_warning_guard",
            "logic_gate_trigger",
            "critical",
            "Coverage-warning guard for stale profile source age, missing component rows, or thin high-grade participation.",
        ),
        (
            "latency_quality",
            ("profiles",),
            ("B",),
            "profile_distribution_concentration_guard",
            "logic_gate_trigger",
            "critical",
            "Concentration guard that flags one-profile dominance before reusing profile pressure as an execution input.",
        ),
        (
            "latency_quality",
            ("profiles",),
            ("B",),
            "profile_distribution_grade_style_balance_guard",
            "logic_gate_trigger",
            "critical",
            "Grade/style balance guard that blocks reuse when S++/S+/S or hedger/outcome_predictor/unknown buckets collapse into one thin subgroup.",
        ),
        (
            "outcome_prediction",
            ("profiles",),
            ("B",),
            "confidence_extreme_only",
            "refreshing_stat",
            "critical",
            "Directional profile signal emitted only when reconstructed distribution is extreme enough to justify outcome use.",
        ),
        (
            "support_resistance",
            ("optionprice",),
            ("C",),
            "price_bucket_rebound_reference",
            "price_reference",
            "critical",
            "Option price bucket reference for repeated 5c/10c touches and reclaim levels.",
        ),
        (
            "support_resistance",
            ("optionprice",),
            ("C",),
            "tail_touch_comeback_reference",
            "price_reference",
            "critical",
            "Tail-touch reference for 1c/5c/10c contact and later 5c/10c/20c comeback ladders.",
        ),
        (
            "grid_spacing",
            ("optionprice",),
            ("C",),
            "realized_range_reference",
            "strategy_parameter",
            "critical",
            "Grid spacing reference from realized Up/Down option range and rolling swing distance.",
        ),
        (
            "liquidity_depth",
            ("optionprice",),
            ("C",),
            "spread_depth_guard",
            "logic_gate_trigger",
            "critical",
            "Liquidity guard based on Up/Down spread, depth, and minimum fillable notional.",
        ),
        (
            "liquidity_depth",
            ("optionprice",),
            ("C",),
            "spread_top3_friction_guard",
            "logic_gate_trigger",
            "critical",
            "Microstructure fillability guard using top-of-book spread plus top3 depth as a realistic friction filter.",
        ),
        (
            "liquidity_depth",
            ("optionprice",),
            ("C",),
            "pair_depth_pressure_fillability_guard",
            "logic_gate_trigger",
            "critical",
            "Pair-depth pressure guard that rejects shallow or one-sided books that would not support realistic bid/ask fills.",
        ),
        (
            "stale_order_review",
            ("optionprice",),
            ("C",),
            "spread_latency_cancel_replace_gate",
            "logic_gate_trigger",
            "critical",
            "Cancel/replace review gate for stale orders when price path, spread, or capture latency invalidates an order.",
        ),
        (
            "grid_type",
            ("optionprice",),
            ("C",),
            "path_efficiency_inversion_selector",
            "strategy_parameter",
            "high",
            "Grid type selector using path efficiency, inversion count, and 40/60 crossing behavior.",
        ),
        (
            "final_minute",
            ("optionprice",),
            ("C",),
            "resolved_vs_comeback_reference",
            "price_reference",
            "high",
            "Final-minute reference separating resolved 0/100 paths from comeback-capable 10c-25c underdogs.",
        ),
        (
            "final_minute",
            ("optionprice",),
            ("C",),
            "tail_time_remaining_reversal_reference",
            "price_reference",
            "high",
            "Final-minute tail reference split by time remaining and 1c/5c/10c comeback-to-5c/10c/20c rates.",
        ),
        (
            "final_minute",
            ("optionprice",),
            ("C",),
            "tail_extreme_rebound_reference",
            "price_reference",
            "high",
            "Deep-tail rebound reference keyed by extreme_sample_count, rebound flips, strong rebound touches, path efficiency, and max swing distance.",
        ),
        (
            "latency_quality",
            ("cryptoprice", "optionprice", "profiles"),
            ("A", "B", "C"),
            "abc_alignment_freshness_gate",
            "logic_gate_trigger",
            "critical",
            "Cross-source freshness and alignment gate before combining crypto, profile, and option references.",
        ),
        (
            "hedge_ratio",
            ("profiles", "optionprice"),
            ("B", "C"),
            "distribution_price_delta_reference",
            "refreshing_stat",
            "critical",
            "Hedge ratio reference combining profile distribution delta with current Up/Down option prices.",
        ),
        (
            "grid_spacing",
            ("cryptoprice", "optionprice"),
            ("A", "C"),
            "crypto_option_volatility_reference",
            "strategy_parameter",
            "critical",
            "Grid spacing reference from crypto volatility and observed option price-path volatility.",
        ),
        (
            "grid_type",
            ("optionprice",),
            ("C",),
            "tail_path_pressure_selector",
            "strategy_parameter",
            "high",
            "Tail selector using extreme samples, rebound flips, strong rebound touches, path efficiency, swing distance, and depth pressure.",
        ),
        (
            "side_start",
            ("profiles", "optionprice"),
            ("B", "C"),
            "pre_event_profile_price_reference",
            "strategy_parameter",
            "high",
            "Pre-event start-side reference from buying-ahead profile pressure and option drift.",
        ),
        (
            "cashout_rebuy",
            ("optionprice",),
            ("C",),
            "profit_ladder_reference",
            "strategy_parameter",
            "high",
            "Cashout/rebuy ladder reference from common option retracement distances and spread constraints.",
        ),
        (
            "cashout_rebuy",
            ("optionprice",),
            ("C",),
            "forward_mark_cashout_viability",
            "logic_gate_trigger",
            "critical",
            "Forward-mark cashout viability gate that requires future bid support beyond entry plus spread drag.",
        ),
        (
            "final_minute",
            ("profiles", "optionprice"),
            ("B", "C"),
            "profile_tail_pressure_alignment",
            "logic_gate_trigger",
            "high",
            "B+C tail gate requiring profile imbalance and option-path comeback pressure to agree before convex underdog exposure.",
        ),
        (
            "final_minute",
            ("profiles", "optionprice"),
            ("B", "C"),
            "profile_pair_depth_tail_alignment",
            "logic_gate_trigger",
            "high",
            "B+C tail gate requiring profile pressure alignment plus meaningful pair-depth pressure before treating a comeback as actionable.",
        ),
        (
            "grid_spacing",
            ("optionprice",),
            ("C",),
            "rolling_range_spread_reference",
            "strategy_parameter",
            "critical",
            "Rolling-range reference that scales scalp spacing from recent 30s/60s range after spread friction.",
        ),
        (
            "side_start",
            ("optionprice",),
            ("C",),
            "entry_price_band_depth_reference",
            "strategy_parameter",
            "high",
            "Entry-band reference for 10c-20c tails, center-band churn, and spread/depth-aware scalp starts.",
        ),
        (
            "trend_regime",
            ("optionprice",),
            ("C",),
            "near50c_churn_imbalance_reference",
            "logic_gate_trigger",
            "high",
            "Center-band churn reference using near-50c sample density, pair-depth pressure, and order-book imbalance.",
        ),
        (
            "latency_quality",
            ("optionprice",),
            ("C",),
            "source_latency_trade_print_guard",
            "logic_gate_trigger",
            "critical",
            "Source-latency and trade-print guard for rejecting stale books that lack executed tape confirmation.",
        ),
        (
            "liquidity_depth",
            ("optionprice",),
            ("C",),
            "top3_pair_depth_pressure_reference",
            "price_reference",
            "critical",
            "Top-3 pair-depth pressure reference measuring whether visible Up/Down depth skew is strong enough to justify a spread-paid scalp.",
        ),
    )
    for signal_type, sources, blocks, variant, purpose, impact, description in building_block_v5s:
        add(
            signal_type=signal_type,
            sources=sources,
            variant=variant,
            purpose=purpose,
            phase="both",
            blocks=blocks,
            target="promotion-quality non-directional building block for strategy construction and live-shadow gating",
            criteria="must pass no-lookahead sample/diversity/hit-rate checks; direct forward return is required only for directional variants",
            unit="decision_frame",
            impact=impact,
            description=description,
            payload={"building_block": True, "directional_entry_claim": signal_type in {"outcome_prediction", "side_start"}},
            frames=("pre_event", "0:30", "1:00", "2:00", "3:00", "4:00"),
            version="v5",
        )

    hedge_floor_variants = (
        (
            "inversion_intensity",
            ("optionprice",),
            ("C",),
            "path_crossing_flip_density",
            "refreshing_stat",
            "critical",
            "Option-path inversion score from crossings, flips, near-50c churn, and rolling range.",
        ),
        (
            "tail_reversal_probability",
            ("optionprice", "profiles"),
            ("B", "C"),
            "underdog_touch_comeback_table",
            "price_reference",
            "high",
            "Protected-tail comeback table for 1c/5c/10c touches conditioned on profile pressure and option-path state.",
        ),
        (
            "grid_viability",
            ("optionprice",),
            ("C",),
            "spread_depth_rebound_budget",
            "logic_gate_trigger",
            "critical",
            "Grid viability gate balancing inversion frequency, spread drag, rebound room, and depth.",
        ),
        (
            "hedge_floor_state",
            ("profiles", "optionprice"),
            ("B", "C"),
            "paired_seed_inventory_floor",
            "refreshing_stat",
            "critical",
            "Current hedge-floor state reconstructed from paired inventory, realized cash, and current prices.",
        ),
        (
            "floor_preserving_order_gate",
            ("optionprice",),
            ("C",),
            "weaker_side_improve_or_preserve",
            "logic_gate_trigger",
            "critical",
            "Order-validity gate that only permits hedge changes which improve the weaker side or preserve the protected floor.",
        ),
        (
            "protected_floor_improvement",
            ("optionprice",),
            ("C",),
            "delta_if_up_down_projection",
            "refreshing_stat",
            "critical",
            "Projected floor delta from candidate buys using if_up += q*(1-p) and if_down -= q*p math.",
        ),
        (
            "surplus_tail_budget",
            ("profiles", "optionprice"),
            ("B", "C"),
            "protected_surplus_only",
            "strategy_parameter",
            "high",
            "Tail-optional budget derived only from guaranteed floor surplus above the protected reserve.",
        ),
        (
            "grid_spacing_from_inversion_stats",
            ("cryptoprice", "optionprice"),
            ("A", "C"),
            "volatility_crossing_scaled",
            "strategy_parameter",
            "critical",
            "Spacing reference from option-path inversion intensity plus crypto/option volatility.",
        ),
        (
            "rebound_enough_to_cashout",
            ("optionprice",),
            ("C",),
            "rolling_range_vs_profit_target",
            "logic_gate_trigger",
            "critical",
            "Cashout gate requiring enough rebound range to clear spread and profit target before rebuy logic activates.",
        ),
    )
    for signal_type, sources, blocks, variant, purpose, impact, description in hedge_floor_variants:
        add(
            signal_type=signal_type,
            sources=sources,
            variant=variant,
            purpose=purpose,
            phase="both",
            blocks=blocks,
            target="hedge-floor building block quality under strict no-lookahead replay and structural fit checks",
            criteria="must produce stable floor-aware references or gates without weakening protected-floor math",
            unit="decision_frame",
            impact=impact,
            description=description,
            payload={"hedge_floor_block": signal_type, "variant": variant, "orders_allowed": False},
            frames=("pre_event", "0:30", "1:00", "2:00", "3:00", "4:00"),
            version="v1",
        )

    hedge_floor_revision_waves = (
        (
            "inversion_intensity",
            ("optionprice",),
            ("C",),
            "tail_touch_rebound_flip_density",
            "refreshing_stat",
            "critical",
            "v2",
            "Empirical inversion reference for tail-touch windows that scores rebound flips, center-band churn, and crossing density only after confirmed 1c/5c/10c underdog stress.",
        ),
        (
            "inversion_intensity",
            ("optionprice",),
            ("C",),
            "forward_cashout_edge_clean_flip_density",
            "refreshing_stat",
            "critical",
            "v3",
            "Empirical inversion reference for tail-touch windows that only credits rebound flips and center-band churn after touched-side forward cashout edge clears friction-adjusted exit quality, matching the forward-edge-clean hedge-floor replay lane.",
        ),
        (
            "tail_reversal_probability",
            ("optionprice", "profiles"),
            ("B", "C"),
            "tail_touch_microstructure_context",
            "price_reference",
            "critical",
            "v2",
            "Empirical tail-touch comeback reference that prefers volatility, spread/depth pressure, and profile-confidence context over generic tail priors.",
        ),
        (
            "grid_viability",
            ("optionprice",),
            ("C",),
            "tail_touch_spread_depth_budget",
            "logic_gate_trigger",
            "critical",
            "v2",
            "Grid viability gate for tail-touch windows that separates genuine rebound room from spread drag and shallow-book false positives.",
        ),
        (
            "hedge_floor_state",
            ("profiles", "optionprice"),
            ("B", "C"),
            "scenario_outcome_confidence_floor",
            "refreshing_stat",
            "critical",
            "v2",
            "Hedge-floor state reference that reconstructs the protected floor using the touched-side scenario outcome while downgrading B-profile pressure to confidence only.",
        ),
        (
            "floor_preserving_order_gate",
            ("optionprice",),
            ("C",),
            "scenario_outcome_floor_preserve",
            "logic_gate_trigger",
            "critical",
            "v2",
            "Order gate that validates floor-preserving hedge math against the tail-touch scenario side instead of generic profile-follow direction.",
        ),
        (
            "surplus_tail_budget",
            ("profiles", "optionprice"),
            ("B", "C"),
            "subgroup_confidence_capped_surplus",
            "strategy_parameter",
            "high",
            "v2",
            "Tail-budget reference that caps protected surplus by subgroup freshness, concentration, and side-coherence quality before spending any convex comeback budget.",
        ),
        (
            "tail_reversal_probability",
            ("optionprice", "profiles"),
            ("B", "C"),
            "tail_touch_subgroup_alignment_context",
            "price_reference",
            "critical",
            "v3",
            "Empirical tail-touch comeback reference that keeps subgroup side tilt, contribution mix, and freshness-conflict state as a confidence overlay on the touched-side comeback table instead of reusing generic profile-majority pressure.",
        ),
        (
            "tail_reversal_probability",
            ("optionprice", "profiles"),
            ("B", "C"),
            "tail_touch_profile_price_context",
            "price_reference",
            "critical",
            "v4",
            "Empirical tail-touch comeback reference that upgrades subgroup alignment with replay-safe reconstructed profile-price delta context, so comeback odds follow touched-side subgroup tilt plus actual profile-price dislocation instead of coarse subgroup agreement alone.",
        ),
        (
            "surplus_tail_budget",
            ("profiles", "optionprice"),
            ("B", "C"),
            "tail_touch_subgroup_alignment_cap",
            "strategy_parameter",
            "high",
            "v3",
            "Protected surplus cap that trims tail budget when the touched-side subgroup mix is stale, one-bucket concentrated, or misaligned with the empirical comeback side even if gross floor surplus remains positive.",
        ),
        (
            "surplus_tail_budget",
            ("profiles", "optionprice"),
            ("B", "C"),
            "tail_touch_profile_price_cap",
            "strategy_parameter",
            "high",
            "v4",
            "Protected surplus cap that also requires replay-safe subgroup profile-price dislocation to agree with the touched-side comeback context before spending protected floor surplus on tail exposure.",
        ),
        (
            "hedge_floor_state",
            ("profiles", "optionprice"),
            ("B", "C"),
            "profile_price_confidence_floor",
            "refreshing_stat",
            "critical",
            "v3",
            "Hedge-floor state reference that keeps scenario-outcome floor math intact while downgrading confidence when subgroup tilt and reconstructed profile-price delta disagree with the touched-side comeback context.",
        ),
        (
            "grid_viability",
            ("optionprice",),
            ("C",),
            "forward_cashout_edge_budget",
            "logic_gate_trigger",
            "critical",
            "v3",
            "Grid-viability gate that requires touched-side forward cashout edge to clear friction-adjusted exit quality instead of trusting inversion density and spread/depth alone.",
        ),
        (
            "floor_preserving_order_gate",
            ("optionprice",),
            ("C",),
            "forward_cashout_edge_floor_preserve",
            "logic_gate_trigger",
            "critical",
            "v3",
            "Order gate that only treats additional hedge-floor inventory as executable when projected forward cashout edge still preserves the protected floor after friction.",
        ),
    )
    for signal_type, sources, blocks, variant, purpose, impact, version, description in hedge_floor_revision_waves:
        baseline_variant = {
            "tail_touch_rebound_flip_density": "path_crossing_flip_density",
            "forward_cashout_edge_clean_flip_density": "tail_touch_rebound_flip_density",
            "tail_touch_microstructure_context": "underdog_touch_comeback_table",
            "tail_touch_spread_depth_budget": "spread_depth_rebound_budget",
            "scenario_outcome_confidence_floor": "paired_seed_inventory_floor",
            "scenario_outcome_floor_preserve": "weaker_side_improve_or_preserve",
            "subgroup_confidence_capped_surplus": "protected_surplus_only",
            "tail_touch_subgroup_alignment_context": "tail_touch_microstructure_context",
            "tail_touch_profile_price_context": "tail_touch_subgroup_alignment_context",
            "tail_touch_subgroup_alignment_cap": "subgroup_confidence_capped_surplus",
            "tail_touch_profile_price_cap": "tail_touch_subgroup_alignment_cap",
            "profile_price_confidence_floor": "scenario_outcome_confidence_floor",
            "forward_cashout_edge_budget": "tail_touch_spread_depth_budget",
            "forward_cashout_edge_floor_preserve": "scenario_outcome_floor_preserve",
        }[variant]
        supersedes_version = {
            "forward_cashout_edge_clean_flip_density": "v2",
            "tail_touch_subgroup_alignment_context": "v2",
            "tail_touch_profile_price_context": "v3",
            "tail_touch_subgroup_alignment_cap": "v2",
            "tail_touch_profile_price_cap": "v3",
            "profile_price_confidence_floor": "v2",
            "forward_cashout_edge_budget": "v2",
            "forward_cashout_edge_floor_preserve": "v2",
        }.get(variant, "v1")
        add(
            signal_type=signal_type,
            sources=sources,
            variant=variant,
            purpose=purpose,
            phase="both",
            blocks=blocks,
            target="hedge-floor tail-touch building blocks that stay empirical, replay-safe, and protected-floor preserving under v3 strategy assumptions",
            criteria="must improve structural replay fit for tail-touch windows without loosening floor-preserving or fillability invariants",
            unit="decision_frame",
            impact=impact,
            description=description,
            payload={"hedge_floor_revision_wave": variant, "empirical_tail_touch_required": True, "orders_allowed": False},
            supersedes_signal_id=build_signal_id(
                family=FAMILY,
                signal_type=signal_type,
                sources=sources,
                variant=baseline_variant,
                version=supersedes_version,
            ),
            frames=("pre_event", "0:30", "1:00", "2:00", "3:00", "4:00"),
            version=version,
        )

    profile_subgroup_revision_waves = (
        (
            "outcome_prediction",
            ("profiles",),
            ("B",),
            "splus_hedger_subgroup_coherent_consensus",
            "refreshing_stat",
            "high",
            "v5",
            build_signal_id(
                family=FAMILY,
                signal_type="outcome_prediction",
                sources=("profiles",),
                variant="splus_hedger_coherent_consensus",
                version="v4",
            ),
            "S+ hedger subgroup-only directional reference when subgroup breadth, method agreement, and pair-sum sanity stay coherent enough for executable follow logic without borrowing S++ assumptions.",
        ),
        (
            "latency_quality",
            ("profiles",),
            ("B",),
            "splus_hedger_subgroup_component_guard",
            "logic_gate_trigger",
            "critical",
            "v5",
            None,
            "Guard S+ hedger subgroup usage when component coverage, freshness, or concentration quality is too weak for replay-safe execution evidence.",
        ),
        (
            "outcome_prediction",
            ("profiles",),
            ("B",),
            "splusplus_hedger_subgroup_coherent_consensus",
            "refreshing_stat",
            "critical",
            "v5",
            None,
            "S++ hedger subgroup-only directional reference when subgroup depth, method agreement, and pair-sum sanity stay coherent enough for executable follow logic.",
        ),
        (
            "latency_quality",
            ("profiles",),
            ("B",),
            "splusplus_hedger_subgroup_depth_freshness_guard",
            "logic_gate_trigger",
            "critical",
            "v5",
            None,
            "Guard S++ hedger subgroup usage when the subgroup is stale, too concentrated, or too thin for replay-safe execution evidence.",
        ),
        (
            "outcome_prediction",
            ("profiles",),
            ("B",),
            "outcome_predictor_subgroup_coherent_consensus",
            "refreshing_stat",
            "high",
            "v5",
            build_signal_id(
                family=FAMILY,
                signal_type="outcome_prediction",
                sources=("profiles",),
                variant="outcome_predictor_coherent_consensus",
                version="v4",
            ),
            "Outcome-predictor subgroup-only reference when style pressure is fresh, non-concentrated, and coherent across weighted methods and component counts.",
        ),
        (
            "latency_quality",
            ("profiles",),
            ("B",),
            "outcome_predictor_subgroup_component_guard",
            "logic_gate_trigger",
            "critical",
            "v5",
            None,
            "Guard outcome-predictor subgroup usage when component coverage, cost-share balance, or freshness quality is too weak for executable reuse.",
        ),
    )
    for (
        signal_type,
        sources,
        blocks,
        variant,
        purpose,
        impact,
        version,
        supersedes_signal_id,
        description,
    ) in profile_subgroup_revision_waves:
        add(
            signal_type=signal_type,
            sources=sources,
            variant=variant,
            purpose=purpose,
            phase="both" if signal_type == "outcome_prediction" else "live",
            blocks=blocks,
            target="B-profile subgroup coherence and coverage quality before S++ or outcome-predictor pressure is reused as an executable signal input",
            criteria="must reject stale or thin subgroup contexts while preserving only the subgroup slices that survive strict replay and method-agreement review",
            unit="event_slug" if signal_type == "outcome_prediction" else "decision_frame",
            impact=impact,
            description=description,
            payload={"profile_subgroup_revision": variant, "requires_component_breakdown": True, "orders_allowed": False},
            parent_signal_id=build_signal_id(
                family=FAMILY,
                signal_type="profile_subgroup_distribution",
                sources=("profiles", "optionprice"),
                variant="grade_style_side_tilt_reference",
                version="v1",
            ),
            supersedes_signal_id=supersedes_signal_id,
            frames=("pre_event", "0:30", "1:00", "2:30", "4:00"),
            version=version,
        )

    add(
        signal_type="profile_subgroup_distribution",
        sources=("profiles", "optionprice"),
        variant="grade_style_side_tilt_reference",
        purpose="refreshing_stat",
        phase="both",
        blocks=("B", "C"),
        target="B-profile subgroup diagnostics that expose grade/style/side tilt before subgroup pressure is reused in hedge-floor or follow/fade execution",
        criteria="must surface subgroup mix, weighted-cost tilt, contribution balance, and stale/conflict flags without implying executable direction when subgroup quality is degraded",
        unit="event_slug",
        impact="critical",
        description="Subgroup-distribution reference exposing S++/S+/outcome-predictor grade/style mix, weighted-cost side tilt, contribution share, refresh age, and stale/conflict warnings alongside option-price context.",
        payload={
            "profile_subgroup_revision": "grade_style_side_tilt_reference",
            "requires_component_breakdown": True,
            "requires_option_context": True,
            "orders_allowed": False,
        },
        frames=("pre_event", "0:30", "1:00", "2:30", "4:00"),
        version="v1",
    )
    profile_subgroup_distribution_signal_id = build_signal_id(
        family=FAMILY,
        signal_type="profile_subgroup_distribution",
        sources=("profiles", "optionprice"),
        variant="grade_style_side_tilt_reference",
        version="v1",
    )

    add(
        signal_type="profile_subgroup_distribution",
        sources=("profiles", "optionprice"),
        variant="method_agreement_concentration_reference",
        purpose="refreshing_stat",
        phase="both",
        blocks=("B", "C"),
        target="B-profile subgroup diagnostics that expose weighting-method agreement and concentration before subgroup pressure is reused in hedge-floor or subgroup-follow execution",
        criteria="must surface subgroup method drift, dominant-bucket concentration, pair-sum sanity, and freshness/conflict warnings without implying executable direction when subgroup quality is degraded",
        unit="event_slug",
        impact="critical",
        description="Subgroup-distribution reference exposing cost/share/count agreement, dominant subgroup concentration, pair-sum drift, refresh age, and touched-side alignment warnings alongside option-price context.",
        payload={
            "profile_subgroup_revision": "method_agreement_concentration_reference",
            "requires_component_breakdown": True,
            "requires_option_context": True,
            "requires_method_agreement": True,
            "orders_allowed": False,
        },
        supersedes_signal_id=profile_subgroup_distribution_signal_id,
        frames=("pre_event", "0:30", "1:00", "2:30", "4:00"),
        version="v2",
    )
    profile_subgroup_distribution_method_signal_id = build_signal_id(
        family=FAMILY,
        signal_type="profile_subgroup_distribution",
        sources=("profiles", "optionprice"),
        variant="method_agreement_concentration_reference",
        version="v2",
    )

    add(
        signal_type="profile_subgroup_distribution",
        sources=("profiles", "optionprice"),
        variant="profile_price_tail_context_reference",
        purpose="refreshing_stat",
        phase="both",
        blocks=("B", "C"),
        target="B-profile subgroup diagnostics that carry replay-safe profile-price tail context before subgroup pressure is reused in hedge-floor tail or subgroup-follow execution",
        criteria="must surface subgroup method agreement, concentration, reconstructed profile-price delta, and touched-side tail-context alignment without implying executable direction when profile-price evidence is degraded",
        unit="event_slug",
        impact="critical",
        description="Subgroup-distribution reference exposing cost/share/count agreement, dominant subgroup concentration, reconstructed profile-price delta buckets, touched-side tail-context alignment, refresh age, and stale/conflict warnings alongside option-price context.",
        payload={
            "profile_subgroup_revision": "profile_price_tail_context_reference",
            "requires_component_breakdown": True,
            "requires_option_context": True,
            "requires_method_agreement": True,
            "requires_profile_price_context": True,
            "empirical_tail_touch_required": True,
            "orders_allowed": False,
        },
        supersedes_signal_id=profile_subgroup_distribution_method_signal_id,
        frames=("pre_event", "0:30", "1:00", "2:30", "4:00"),
        version="v3",
    )
    profile_subgroup_distribution_profile_price_signal_id = build_signal_id(
        family=FAMILY,
        signal_type="profile_subgroup_distribution",
        sources=("profiles", "optionprice"),
        variant="profile_price_tail_context_reference",
        version="v3",
    )

    add(
        signal_type="profile_subgroup_distribution",
        sources=("profiles", "optionprice"),
        variant="profile_price_execution_context_reference",
        purpose="refreshing_stat",
        phase="both",
        blocks=("B", "C"),
        target="B-profile subgroup diagnostics that carry replay-safe profile-price plus execution-friction context before subgroup pressure is reused in hedge-floor tail or subgroup-follow execution",
        criteria="must surface subgroup method agreement, concentration, reconstructed profile-price delta, and execution-friction alignment without implying executable direction when fill-quality evidence is degraded",
        unit="event_slug",
        impact="critical",
        description="Subgroup-distribution reference exposing cost/share/count agreement, dominant subgroup concentration, reconstructed profile-price delta buckets, execution-friction alignment, refresh age, and stale/conflict warnings alongside option-price context.",
        payload={
            "profile_subgroup_revision": "profile_price_execution_context_reference",
            "requires_component_breakdown": True,
            "requires_option_context": True,
            "requires_method_agreement": True,
            "requires_profile_price_context": True,
            "requires_execution_context": True,
            "empirical_tail_touch_required": True,
            "orders_allowed": False,
        },
        supersedes_signal_id=profile_subgroup_distribution_profile_price_signal_id,
        frames=("pre_event", "0:30", "1:00", "2:30", "4:00"),
        version="v4",
    )

    add(
        signal_type="latency_quality",
        sources=("profiles", "optionprice"),
        variant="tail_touch_subgroup_conflict_guard",
        purpose="logic_gate_trigger",
        phase="live",
        blocks=("B", "C"),
        target="tail-touch subgroup confidence gating before B-profile style pressure is reused in hedge-floor tail or subgroup-follow execution",
        criteria="must block stale, one-bucket, or touched-side-misaligned subgroup contexts before they are treated as executable profile confidence",
        unit="decision_frame",
        impact="critical",
        description="Guard that rejects tail-touch subgroup confidence reuse when grade/style side tilt, contribution share, or freshness/conflict diagnostics disagree with the empirical touched-side comeback context.",
        payload={
            "profile_subgroup_revision": "tail_touch_subgroup_conflict_guard",
            "requires_component_breakdown": True,
            "requires_option_context": True,
            "empirical_tail_touch_required": True,
            "orders_allowed": False,
        },
        parent_signal_id=profile_subgroup_distribution_signal_id,
        frames=("0:30", "1:00", "2:30", "4:00"),
        version="v5",
    )

    add(
        signal_type="latency_quality",
        sources=("profiles", "optionprice"),
        variant="subgroup_method_agreement_guard",
        purpose="logic_gate_trigger",
        phase="live",
        blocks=("B", "C"),
        target="subgroup method-agreement gating before B-profile subgroup pressure is reused in hedge-floor tail or subgroup-follow execution",
        criteria="must block subgroup contexts when cost/share/count methods diverge, one bucket dominates, or pair-sum drift and freshness warnings undermine executable confidence",
        unit="decision_frame",
        impact="critical",
        description="Guard that rejects subgroup confidence reuse when weighting methods disagree, one subgroup dominates the evidence set, or pair-sum/freshness warnings make the subgroup distribution non-executable.",
        payload={
            "profile_subgroup_revision": "subgroup_method_agreement_guard",
            "requires_component_breakdown": True,
            "requires_option_context": True,
            "requires_method_agreement": True,
            "orders_allowed": False,
        },
        parent_signal_id=profile_subgroup_distribution_method_signal_id,
        frames=("0:30", "1:00", "2:30", "4:00"),
        version="v5",
    )

    return tuple(rows)


EXPANDED_SIGNAL_SPECS = _build_expanded_signal_specs()
ALL_SIGNAL_SPECS: tuple[SignalCandidateSpec, ...] = FIRST_BATCH_SIGNAL_SPECS + EXPANDED_SIGNAL_SPECS

_BY_ID = {spec.signal_id: spec for spec in ALL_SIGNAL_SPECS}
